### ISSUE TITLE
11/10 Comprensión de las peticiones del proyecto.

### ISSUE THREAD

**Issue by marinagasco** [mtoledo-rgb/proyecto_spoty-api#5]

**Comment by mtoledo-rgb** [comment]
**OBJETIVOS TÉCNICOS**
- Consolidar los conocimientos de Python y SQL.
- Implementar control de versiones en equipo, usando Git y GitHub.

**FASES**
Fase 1. Extracción de Datos:
- [ ] Extracción de Datos desde la API de Spotify.
- [ ] Extracción de detalles de artistas con la API de MusicBrainz.
- [ ] Extracción de detalles de artistas con la API de last.fm

Fase 2. Organización y Almacenamiento de Datos:
- [ ] Diseño de estructura en SQL para las Bases de Datos (BBDD).
- [ ] Inserción de las BBDD en SQL.

Fase 3. Análisis y Consultas de Datos:
- ¿Qué género tiene el promedio más alto de reproducciones?.
- ¿Cuántos artistas pertenecen a cada género en la base de datos y cuál es el género con más artistas?.
- ¿Cuántos artistas tienen menos de 100,000 reproducciones?
- ¿Cuál es el artista con más Listeners?.
- ¿Qué país tiene mas artistas? (ordenar por cantidad).
- ¿Qué artista estuvo mas tiempo y cuantas canciones tiene en el rango extraído de información?

**PLANIFICACIÓN DEL PROYECTO**
- [ ] Crear la infraestructura necesaria: repositorio en GitHub y con acceso para todos los miembros del equipo.
- [ ] Extraer datos de distintas fuentes de datos y creación de una Base de Datos.
- [ ] Tener la extracción de datos, creación de la Base de Datos e inserción de datos automatizada en funciones **(obligatorio)** y clases **(optativo)**.
- [ ] Tener en el repositorio de GitHub todo el código del desarrollo del proyecto.


**FALTAN LAS ÚLTIMAS PARTES**
